version: 2.1

# Minor change 'test_104' to see how change config.yml from CircleCI GUI
parameters:
  run-schedule:
    type: boolean
    default: false

# Define the jobs we want to run for this project
jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.10"
    steps:
      - checkout
      - run: python3 main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.10"
    steps:
      - checkout
      - run: python3 main_test.py

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

  scheduled_workflow:
    when: << pipeline.parameters.run-schedule >>
    jobs:
      - build
